//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRTG.Sensors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRTG.Sensors.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create index if not exists ix_exceptions on exceptions
        ///(
        ///	sensor_id,
        ///	exception_time
        ///).
        /// </summary>
        internal static string schema_exceptions_index {
            get {
                return ResourceManager.GetString("schema_exceptions_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists exceptions
        ///(
        ///    sensor_id           INTEGER,
        ///    exception_time		INTEGER,
        ///	exception_text		TEXT NULL,
        ///	stacktrace			TEXT NULL,
        ///	cleared             INTEGER,
        ///).
        /// </summary>
        internal static string schema_exceptions_table {
            get {
                return ResourceManager.GetString("schema_exceptions_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create index if not exists ix_measurements on measurements
        ///(
        ///    sensor_id,
        ///	measurement_time
        ///).
        /// </summary>
        internal static string schema_measurements_index {
            get {
                return ResourceManager.GetString("schema_measurements_index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table if not exists measurements
        ///(
        ///    sensor_id           INTEGER,
        ///    measurement_time	INTEGER,
        ///	value				NUMERIC,
        ///	collection_time_ms	INTEGER
        ///).
        /// </summary>
        internal static string schema_measurements_table {
            get {
                return ResourceManager.GetString("schema_measurements_table", resourceCulture);
            }
        }
    }
}
